
export const ventas_anuales_tienda = {
    Enero:[],
    Febrero:[],
    Marzo:[],
    Abril:[],
    Mayo:[],
    Junio:[],
    Julio:[
        {
        product_id: "1",
        name: "Remera Animal",
        qty_sell: 11,
        unit_price: 2500,
        category: "Indumentaria",
        },
        {
        product_id: "2",
        name: "Remera No Pain No Gain",
        qty_sell: 14,
        unit_price: 2500,
        category: "Indumentaria",
        },
        {
        product_id: "3",
        name: "Gorra Animal",
        qty_sell: 21,
        unit_price: 1500,
        category: "Indumentaria",
        },
        {   
        product_id: "4",
        name: "Mancuerna",
        qty_sell: 16, 
        unit_price: 4500,
        category: "Accesorios",
        },
        {
        product_id: "5",
        name: "Soga",
        qty_sell: 9, 
        unit_price: 2200,
        category: "Accesorios",
        },
        {
        product_id: "6",
        name: "Kit Boxeo",
        qty_sell: 9, 
        unit_price: 2200,
        category: "Accesorios",
        },
        {
        product_id: "7",
        name: "Suplemento proteico",
        qty_sell: 22, 
        unit_price: 5000,
        category: "Suplementos",
        }
    ],
    Agosto:[
        {
            product_id: "1",
            name: "Remera Animal",
            qty_sell: 30,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "2",
            name: "Remera No Pain No Gain",
            qty_sell: 20,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "3",
            name: "Gorra Animal",
            qty_sell: 6,
            unit_price: 1500,
            category: "Indumentaria",
        },
        {   
            product_id: "4",
            name: "Mancuerna",
            qty_sell: 15, 
            unit_price: 4500,
            category: "Accesorios",
        },
        {
            product_id: "5",
            name: "Soga",
            qty_sell: 28, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "6",
            name: "Kit Boxeo",
            qty_sell: 8, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "7",
            name: "Suplemento proteico",
            qty_sell: 10, 
            unit_price: 5000,
            category: "Suplementos",
        }
    ],
    Setiembre:[
        {
            product_id: "1",
            name: "Remera Animal",
            qty_sell: 17,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "2",
            name: "Remera No Pain No Gain",
            qty_sell: 25,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "3",
            name: "Gorra Animal",
            qty_sell: 36,
            unit_price: 1500,
            category: "Indumentaria",
        },
        {   
            product_id: "4",
            name: "Mancuerna",
            qty_sell: 10, 
            unit_price: 4500,
            category: "Accesorios",
        },
        {
            product_id: "5",
            name: "Soga",
            qty_sell: 18, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "6",
            name: "Kit Boxeo",
            qty_sell: 6, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "7",
            name: "Suplemento proteico",
            qty_sell: 12, 
            unit_price: 5000,
            category: "Suplementos",
        }
    ],
    Octubre:[
        {
            product_id: "1",
            name: "Remera Animal",
            qty_sell: 19,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "2",
            name: "Remera No Pain No Gain",
            qty_sell: 20,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "3",
            name: "Gorra Animal",
            qty_sell: 28,
            unit_price: 1500,
            category: "Indumentaria",
        },
        {   
            product_id: "4",
            name: "Mancuerna",
            qty_sell: 6, 
            unit_price: 4500,
            category: "Accesorios",
        },
        {
            product_id: "5",
            name: "Soga",
            qty_sell: 20, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "6",
            name: "Kit Boxeo",
            qty_sell: 5, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "7",
            name: "Suplemento proteico",
            qty_sell: 14, 
            unit_price: 5000,
            category: "Suplementos",
        }
    ],
    Noviembre:[
        {
            product_id: "1",
            name: "Remera Animal",
            qty_sell: 14,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "2",
            name: "Remera No Pain No Gain",
            qty_sell: 21,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "3",
            name: "Gorra Animal",
            qty_sell: 17,
            unit_price: 1500,
            category: "Indumentaria",
        },
        {   
            product_id: "4",
            name: "Mancuerna",
            qty_sell: 10, 
            unit_price: 4500,
            category: "Accesorios",
        },
        {
            product_id: "5",
            name: "Soga",
            qty_sell: 16, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "6",
            name: "Kit Boxeo",
            qty_sell: 7, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "7",
            name: "Suplemento proteico",
            qty_sell: 20, 
            unit_price: 5000,
            category: "Suplementos",
        }
    ],
    Diciembre:[
        {
            product_id: "1",
            name: "Remera Animal",
            qty_sell: 2,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "2",
            name: "Remera No Pain No Gain",
            qty_sell: 0,
            unit_price: 2500,
            category: "Indumentaria",
        },
        {
            product_id: "3",
            name: "Gorra Animal",
            qty_sell: 1,
            unit_price: 1500,
            category: "Indumentaria",
        },
        {   
            product_id: "4",
            name: "Mancuerna",
            qty_sell: 2, 
            unit_price: 4500,
            category: "Accesorios",
        },
        {
            product_id: "5",
            name: "Soga",
            qty_sell: 1, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "6",
            name: "Kit Boxeo",
            qty_sell: 0, 
            unit_price: 2200,
            category: "Accesorios",
        },
        {
            product_id: "7",
            name: "Suplemento proteico",
            qty_sell: 2, 
            unit_price: 5000,
            category: "Suplementos",
        }
    ],
}